theme: minimalist-theme
markdown: kramdown
#paginate: 5
#paginate_path: "/blog/page:num/"
collections:
    authors:
        output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

id_google_analytics: UA-158530510-1
disqus_url: https://surlescocottes-1.disqus.com/embed.js
title: surlescocottes
description: ride, dev and other stories
url: https://surlescocottes.xyz
locale: fr

social:
  linkedin: yannickfrancois
  github: YannickDurden
  instagram: YannickDurden
  strava: /16018371

header:
  title: surlescocottes
  subtitle: ride, dev & other stories

footer:
  text: Yannick

index:
  title: Nouvelles

about:
  username: Yannick
  subtitle: Epicurien à bicyclette

permalink: /:title/

paginate: 4
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate